### ISSUE TITLE
Woops, you've got one already!

### ISSUE THREAD

**Issue by bluefeet** [robn/Test-Consul#1]
Hi Rob - I just created this:

https://github.com/bluefeet/Test-Consul

And then when it didn't get indexed by CPAN I realized one already existed.  I don't know why, I just assumed it did not exist.  Anyways, could we work on this a bit?  I'm pretty sure my implementation is a bit more "drop in and go", and provides a couple extra bells and whistles.  For example, yours uses a datadir, and if not specified which data dir, it automatically uses a static one which would be a big problem when tests are run in parallel.

**Comment by robn** [comment]
Interesting!

I don't care strongly about this package. I'm certainly maintaining it, but only just enough to support my [Consul](https://metacpan.org/pod/Consul) and [AnyEvent::Consul](https://metacpan.org/pod/AnyEvent::Consul) packages.

So I'd be happy to either take patches against my own version to add the features you need, or hand the entire package over to you. The latter probably makes the most sense if you're planning to maintain it properly (you seem quite prolific on CPAN, so I have no particular concerns there).

What would work best for you?

**Comment by bluefeet** [comment]
I'd opt to leave it in your hands since Consul and AnyEvent::Consul depend on it so much.  How about I make you a pull request and make some backwards-compatible improvements.  Thanks man!

**Comment by bluefeet** [comment]
OK, pull request in #2.
